import { getCycleRange } from '../lib/cycle'
import { financeDb, newId } from './db'
import type { Category, FixedCost } from './types'

/**
 * 고정비 쿼리 — spec-finance-v0.2.md §5.6
 * isActive는 인덱스가 아니라 메모리에서 거른다(§3.1).
 */

/** 화면용: 고정비 + 표시 시점에 붙인 카테고리 */
export interface FixedCostItem extends FixedCost {
  category: Category | undefined
}

export async function listFixedCosts(): Promise<FixedCostItem[]> {
  const costs = await financeDb.fixedCosts.toArray()
  // IndexedDB에는 조인이 없다 — 필요한 카테고리만 한 번에 가져와 앱에서 붙인다
  const categories = await financeDb.categories.bulkGet(
    costs.map((cost) => cost.categoryId),
  )
  return costs
    .map((cost, i) => ({ ...cost, category: categories[i] }))
    .sort(
      (a, b) => (a.category?.sortOrder ?? 0) - (b.category?.sortOrder ?? 0),
    )
}

export async function createFixedCost(input: {
  categoryId: string
  amount: number
  dayOfMonth: number
  startCycle: string
  endCycle?: string
  note?: string
}): Promise<string> {
  const id = newId()
  await financeDb.fixedCosts.add({ id, isActive: true, ...input })
  return id
}

export async function updateFixedCost(
  id: string,
  patch: Partial<Omit<FixedCost, 'id'>>,
): Promise<void> {
  await financeDb.fixedCosts.update(id, patch)
}

export async function deleteFixedCost(id: string): Promise<void> {
  await financeDb.fixedCosts.delete(id)
}

/**
 * 이 사이클의 고정비 거래를 만든다 — §5.6
 *
 * 사이클이 시작되는 순간 앱이 켜져 있으리라는 보장이 없으므로, 앱 진입 시
 * 아직 없는 것만 소급해 만든다. 중복 생성은 복합 인덱스 [cycleKey+fixedCostId]로
 * 막는다. 이미 있으면 건너뛴다.
 *
 * startCycle 이전, endCycle 이후 사이클에는 만들지 않는다.
 */
export async function ensureFixedCostTransactions(
  cycleKey: string,
  payday: number,
): Promise<number> {
  return financeDb.transaction(
    'rw',
    financeDb.fixedCosts,
    financeDb.categories,
    financeDb.transactions,
    async () => {
      const costs = await financeDb.fixedCosts.toArray()
      const active = costs.filter(
        (cost) =>
          cost.isActive &&
          cost.startCycle <= cycleKey &&
          (cost.endCycle === undefined || cycleKey <= cost.endCycle),
      )
      if (active.length === 0) return 0

      const categories = await financeDb.categories.bulkGet(
        active.map((cost) => cost.categoryId),
      )
      const { start, end } = getCycleRange(cycleKey, payday)
      let created = 0

      for (const [index, cost] of active.entries()) {
        const category = categories[index]
        if (!category) continue

        const existing = await financeDb.transactions
          .where('[cycleKey+fixedCostId]')
          .equals([cycleKey, cost.id])
          .count()
        if (existing > 0) continue

        await financeDb.transactions.add({
          id: newId(),
          date: dateInCycle(cost.dayOfMonth, start, end),
          cycleKey,
          type: category.type,
          categoryId: cost.categoryId,
          amount: cost.amount,
          isFixed: true,
          isAutoGenerated: true,
          fixedCostId: cost.id,
        })
        created++
      }
      return created
    },
  )
}

/**
 * 고정비의 결제일을 사이클 안의 실제 날짜로 옮긴다.
 * 사이클이 달을 걸치므로(25일~익월 24일) 결제일이 어느 달에 속하는지 갈린다.
 */
function dateInCycle(dayOfMonth: number, start: string, end: string): string {
  const [startYear, startMonth] = start.split('-').map(Number)
  const candidate = `${pad4(startYear)}-${pad2(startMonth)}-${pad2(dayOfMonth)}`
  if (candidate >= start && candidate <= end) return candidate

  // 사이클 시작월에 없으면 다음 달이다
  const nextMonth = startMonth === 12 ? 1 : startMonth + 1
  const nextYear = startMonth === 12 ? startYear + 1 : startYear
  const next = `${pad4(nextYear)}-${pad2(nextMonth)}-${pad2(dayOfMonth)}`
  return next >= start && next <= end ? next : start
}

function pad2(value: number): string {
  return String(value).padStart(2, '0')
}

function pad4(value: number): string {
  return String(value).padStart(4, '0')
}
