import { getCycleRange } from '../lib/cycle'
import { financeDb, newId } from './db'
import type { Asset, Category, Debt, FixedCost } from './types'

/**
 * 고정비 쿼리 — spec-finance-v0.2.md §5.6
 * isActive는 인덱스가 아니라 메모리에서 거른다(§3.1).
 */

/** 화면용: 고정비 + 표시 시점에 붙인 카테고리·연결 대상 */
export interface FixedCostItem extends FixedCost {
  category: Category | undefined
  linkedDebt: Debt | undefined
  linkedAsset: Asset | undefined
}

export async function listFixedCosts(): Promise<FixedCostItem[]> {
  const costs = await financeDb.fixedCosts.toArray()
  // IndexedDB에는 조인이 없다 — 필요한 것만 한 번에 가져와 앱에서 붙인다
  const [categories, debts, assets] = await Promise.all([
    financeDb.categories.bulkGet(costs.map((cost) => cost.categoryId)),
    financeDb.debts.toArray(),
    financeDb.assets.toArray(),
  ])
  const debtById = new Map(debts.map((debt) => [debt.id, debt]))
  const assetById = new Map(assets.map((asset) => [asset.id, asset]))

  return costs
    .map((cost, i) => ({
      ...cost,
      category: categories[i],
      linkedDebt: cost.linkedDebtId
        ? debtById.get(cost.linkedDebtId)
        : undefined,
      linkedAsset: cost.linkedAssetId
        ? assetById.get(cost.linkedAssetId)
        : undefined,
    }))
    .sort(
      (a, b) => (a.category?.sortOrder ?? 0) - (b.category?.sortOrder ?? 0),
    )
}

export async function createFixedCost(input: {
  categoryId: string
  amount: number
  dayOfMonth: number
  startCycle: string
  endCycle?: string
  note?: string
  linkedDebtId?: string
  linkedAssetId?: string
}): Promise<string> {
  const id = newId()
  await financeDb.fixedCosts.add({ id, isActive: true, ...input })
  return id
}

export async function updateFixedCost(
  id: string,
  patch: Partial<Omit<FixedCost, 'id'>>,
): Promise<void> {
  await financeDb.fixedCosts.update(id, patch)
}

export async function deleteFixedCost(id: string): Promise<void> {
  await financeDb.fixedCosts.delete(id)
}

/**
 * 이 사이클의 고정비 거래를 만든다 — §5.6
 *
 * 사이클이 시작되는 순간 앱이 켜져 있으리라는 보장이 없으므로, 앱 진입 시
 * 아직 없는 것만 소급해 만든다. 중복 생성은 복합 인덱스 [cycleKey+fixedCostId]로
 * 막는다. 이미 있으면 건너뛴다.
 *
 * **연결된 부채·자산의 잔액도 함께 갱신한다.** 매달 고정으로 빠지거나 들어오는
 * 돈인데 잔액을 손으로 고쳐야 하면 자산 화면이 금방 낡는다. 거래를 만들지
 * 않고 건너뛴 고정비는 잔액도 건드리지 않으므로 여러 번 눌러도 안전하다.
 *
 * startCycle 이전, endCycle 이후 사이클에는 만들지 않는다.
 */
export interface ApplyResult {
  /** 만든 거래 수 */
  created: number
  /** 잔액을 갱신한 부채 수 */
  debtsUpdated: number
  /** 잔액을 갱신한 자산 수 */
  assetsUpdated: number
}

export async function ensureFixedCostTransactions(
  cycleKey: string,
  payday: number,
): Promise<ApplyResult> {
  return financeDb.transaction(
    'rw',
    [
      financeDb.fixedCosts,
      financeDb.categories,
      financeDb.transactions,
      financeDb.debts,
      financeDb.assets,
    ],
    async () => {
      const result: ApplyResult = {
        created: 0,
        debtsUpdated: 0,
        assetsUpdated: 0,
      }

      const costs = await financeDb.fixedCosts.toArray()
      const active = costs.filter(
        (cost) =>
          cost.isActive &&
          cost.startCycle <= cycleKey &&
          (cost.endCycle === undefined || cycleKey <= cost.endCycle),
      )
      if (active.length === 0) return result

      const categories = await financeDb.categories.bulkGet(
        active.map((cost) => cost.categoryId),
      )
      const { start, end } = getCycleRange(cycleKey, payday)
      const now = Date.now()

      for (const [index, cost] of active.entries()) {
        const category = categories[index]
        if (!category) continue

        const existing = await financeDb.transactions
          .where('[cycleKey+fixedCostId]')
          .equals([cycleKey, cost.id])
          .count()
        if (existing > 0) continue

        await financeDb.transactions.add({
          id: newId(),
          date: dateInCycle(cost.dayOfMonth, start, end),
          cycleKey,
          type: category.type,
          categoryId: cost.categoryId,
          amount: cost.amount,
          isFixed: true,
          isAutoGenerated: true,
          fixedCostId: cost.id,
        })
        result.created++

        // 부채는 줄고 자산은 늘어난다. 0 아래로는 내려가지 않는다.
        if (cost.linkedDebtId) {
          const debt = await financeDb.debts.get(cost.linkedDebtId)
          if (debt) {
            await financeDb.debts.update(debt.id, {
              balance: Math.max(0, debt.balance - cost.amount),
            })
            result.debtsUpdated++
          }
        }
        if (cost.linkedAssetId) {
          const asset = await financeDb.assets.get(cost.linkedAssetId)
          if (asset) {
            await financeDb.assets.update(asset.id, {
              balance: asset.balance + cost.amount,
              updatedAt: now,
            })
            result.assetsUpdated++
          }
        }
      }
      return result
    },
  )
}

/**
 * 원천 차감분으로 부채를 줄인다 — §2.3.1
 *
 * 급여에서 바로 빠지는 대출 원금은 Transaction을 만들지 않는다(만들면 저축률이
 * 이중 계산된다). 그래서 거래 존재 여부로 중복을 판단할 수 없고,
 * `appliedDeductions`에 적용 기록을 따로 남긴다.
 */
export async function applyWithheldDeductions(
  cycleKey: string,
): Promise<number> {
  return financeDb.transaction(
    'rw',
    [financeDb.incomeSettings, financeDb.debts, financeDb.appliedDeductions],
    async () => {
      const income = await financeDb.incomeSettings.get('default')
      const linked = (income?.deductions ?? []).filter(
        (deduction) => deduction.isTransfer && deduction.linkedDebtId,
      )
      if (linked.length === 0) return 0

      let applied = 0
      for (const deduction of linked) {
        const id = `${cycleKey}:${deduction.label}`
        if (await financeDb.appliedDeductions.get(id)) continue

        const debt = await financeDb.debts.get(deduction.linkedDebtId!)
        if (!debt) continue

        await financeDb.debts.update(debt.id, {
          balance: Math.max(0, debt.balance - deduction.amount),
        })
        await financeDb.appliedDeductions.add({
          id,
          cycleKey,
          label: deduction.label,
          debtId: debt.id,
          amount: deduction.amount,
          appliedAt: Date.now(),
        })
        applied++
      }
      return applied
    },
  )
}

/** 이 사이클에 원천 차감을 이미 적용했는지 — 화면 표시용 */
export async function countAppliedDeductions(
  cycleKey: string,
): Promise<number> {
  return financeDb.appliedDeductions.where('cycleKey').equals(cycleKey).count()
}

/**
 * 고정비의 결제일을 사이클 안의 실제 날짜로 옮긴다.
 * 사이클이 달을 걸치므로(25일~익월 24일) 결제일이 어느 달에 속하는지 갈린다.
 */
function dateInCycle(dayOfMonth: number, start: string, end: string): string {
  const [startYear, startMonth] = start.split('-').map(Number)
  const candidate = `${pad4(startYear)}-${pad2(startMonth)}-${pad2(dayOfMonth)}`
  if (candidate >= start && candidate <= end) return candidate

  // 사이클 시작월에 없으면 다음 달이다
  const nextMonth = startMonth === 12 ? 1 : startMonth + 1
  const nextYear = startMonth === 12 ? startYear + 1 : startYear
  const next = `${pad4(nextYear)}-${pad2(nextMonth)}-${pad2(dayOfMonth)}`
  return next >= start && next <= end ? next : start
}

function pad2(value: number): string {
  return String(value).padStart(2, '0')
}

function pad4(value: number): string {
  return String(value).padStart(4, '0')
}
