import { getCycleKey } from '../lib/cycle'
import { financeDb, newId } from './db'
import type { Transaction, TxType } from './types'

/**
 * 거래 쿼리 — 사이클 집계는 복합 인덱스 [cycleKey+type]과
 * [cycleKey+categoryId]가 전담한다(§3.1).
 */

export interface TransactionInput {
  date: string
  type: TxType
  categoryId: string
  amount: number
  memo?: string
  isFixed?: boolean
}

export async function createTransaction(
  input: TransactionInput,
  payday: number,
): Promise<string> {
  const id = newId()
  await financeDb.transactions.add({
    id,
    date: input.date,
    // 저장 시점에 계산해 둔다. 급여일이 바뀌면 일괄 재계산한다(§2.1)
    cycleKey: getCycleKey(input.date, payday),
    type: input.type,
    categoryId: input.categoryId,
    amount: Math.trunc(input.amount),
    memo: input.memo?.trim() || undefined,
    isFixed: input.isFixed ?? false,
    isAutoGenerated: false,
  })
  return id
}

export async function updateTransaction(
  id: string,
  input: TransactionInput,
  payday: number,
): Promise<void> {
  await financeDb.transactions.update(id, {
    date: input.date,
    cycleKey: getCycleKey(input.date, payday),
    type: input.type,
    categoryId: input.categoryId,
    amount: Math.trunc(input.amount),
    memo: input.memo?.trim() || undefined,
    isFixed: input.isFixed ?? false,
  })
}

export async function deleteTransaction(id: string): Promise<void> {
  await financeDb.transactions.delete(id)
}

export function listTransactionsInCycle(
  cycleKey: string,
): Promise<Transaction[]> {
  return financeDb.transactions
    .where('cycleKey')
    .equals(cycleKey)
    .reverse()
    .sortBy('date')
}

/** 주간 입력 화면용 — date 인덱스로 범위 조회한다 */
export function listTransactionsBetween(
  from: string,
  to: string,
): Promise<Transaction[]> {
  return financeDb.transactions
    .where('date')
    .between(from, to, true, true)
    .reverse()
    .sortBy('date')
}

/** 오입력 즉시 확인용 — 최근 입력 몇 건(§5.2) */
export function listRecentTransactions(limit = 5): Promise<Transaction[]> {
  return financeDb.transactions
    .orderBy('date')
    .reverse()
    .limit(limit)
    .toArray()
}

/** 퀵버튼 정렬용 — 카테고리별 사용 빈도(§5.2) */
export async function countUsageByCategory(): Promise<Map<string, number>> {
  const all = await financeDb.transactions.toArray()
  const counts = new Map<string, number>()
  for (const tx of all) {
    counts.set(tx.categoryId, (counts.get(tx.categoryId) ?? 0) + 1)
  }
  return counts
}

/**
 * 급여일이 바뀌면 저장된 모든 cycleKey가 틀어진다. 전부 다시 계산한다(§2.1).
 * 바뀐 건수를 돌려주어 확인 다이얼로그에 쓴다.
 */
export async function recalculateAllCycleKeys(
  payday: number,
): Promise<number> {
  return financeDb.transaction('rw', financeDb.transactions, async () => {
    const all = await financeDb.transactions.toArray()
    const changed = all
      .map((tx) => ({ ...tx, cycleKey: getCycleKey(tx.date, payday) }))
      .filter((tx, i) => tx.cycleKey !== all[i].cycleKey)
    if (changed.length > 0) await financeDb.transactions.bulkPut(changed)
    return changed.length
  })
}
