/**
 * 가계부 도메인 엔티티 — spec-finance-v0.2.md §3.2
 *
 * 금액은 전부 원 단위 정수다(§2.4). 부동소수 오차를 원천 차단한다.
 * 날짜는 'YYYY-MM-DD' 문자열, 타임스탬프는 epoch ms(number)로 운동 쪽 규약과 같다.
 */

export type TxType = 'EXPENSE' | 'SAVING' | 'TRANSFER' | 'INCOME'

export type AssetKind =
  | 'SAVINGS'
  | 'INVESTMENT'
  | 'PENSION'
  | 'CASH'
  | 'DEPOSIT'

export interface Transaction {
  id: string
  /** "2026-10-03" */
  date: string
  /** "2026-10" — 저장 시 계산하고, 급여일이 바뀌면 재계산한다(§2.1) */
  cycleKey: string
  type: TxType
  categoryId: string
  amount: number
  memo?: string
  isFixed: boolean
  isAutoGenerated: boolean
  /** 어느 고정비에서 나왔는지. 중복 생성 방지의 실제 키다(§5.6) */
  fixedCostId?: string
}

/** 카테고리를 묶는 상위 분류. '차량' 아래 '차량 할부 원금'처럼 쓴다. */
export interface Group {
  id: string
  name: string
  sortOrder: number
}

export interface Category {
  id: string
  name: string
  groupId: string
  type: TxType
  /** 월 예산 */
  budget: number
  isFixed: boolean
  sortOrder: number
  isArchived: boolean
}

/** 매월 반복되는 고정비 — 사이클 시작 시 Transaction을 자동 생성한다 */
export interface FixedCost {
  id: string
  categoryId: string
  amount: number
  dayOfMonth: number
  isActive: boolean
  /** "2026-10" */
  startCycle: string
  endCycle?: string
  note?: string
}

export interface Asset {
  id: string
  name: string
  kind: AssetKind
  balance: number
  /** 수익률 계산용 */
  principal?: number
  updatedAt: number
  /** 목표 시점에 현금화 가능 여부 */
  isLiquidByTarget: boolean
  note?: string
}

export interface Debt {
  id: string
  name: string
  balance: number
  /** 학자금처럼 원금을 모르는 경우가 있다(§4.6) */
  originalAmount?: number
  /** 연 %. 〃 */
  interestRate?: number
  monthlyPayment: number
  monthlyPrincipal: number
  monthlyInterest: number
  /** "2030-10" */
  expectedPayoff?: string
  countsInDTI: boolean
}

export interface Goal {
  id: string
  name: string
  /** "2029-03" */
  targetDate: string
  targetAmount: number
  note?: string
}

/** 순자산 스냅샷 */
export interface NetWorthSnapshot {
  /** 기본키. 사이클당 한 건이라 다시 찍어도 덮어쓴다 */
  cycleKey: string
  totalAssets: number
  totalDebts: number
  netWorth: number
  /** 실제로 기록한 시각 */
  capturedAt: number
  /**
   * 이 금액이 어느 날 기준인가 ('YYYY-MM-DD').
   * 사이클이 끝나는 날에 맞춰 자산을 갱신하기 어렵다. 며칠 지나 입력하더라도
   * 기준일을 남겨 두면 추이 그래프를 읽을 때 근거가 된다.
   */
  asOf?: string
}

/**
 * 사이클 총예산 — 카테고리 예산 합계와 별도로 잡는다.
 *
 * 카테고리별 예산은 항목마다 얼마를 쓸지의 계획이고, 사이클 총예산은
 * "이번 달 전체로 얼마까지"라는 상한이다. 둘은 다를 수 있다.
 * 설정하지 않은 사이클은 카테고리 합계를 쓴다.
 */
export interface CycleBudget {
  /** 기본키. "2026-10" */
  cycleKey: string
  amount: number
}

export interface Deduction {
  label: string
  amount: number
  /**
   * 부채 원금 상환처럼 순자산이 되는 공제인가.
   * 저축률의 분자와 총소득 분모를 여기서 만든다(§2.3.1).
   */
  isTransfer: boolean
}

/** 소득 설정 — id가 'default'인 단일 레코드 */
export interface IncomeSetting {
  id: 'default'
  grossPay: number
  netPay: number
  /** 급여일. 기본 25. 상수가 아니라 설정값이다(§2.1) */
  payday: number
  deductions: Deduction[]
}
